gregs stuff working, needs to be cleaned up

diff --git a/wincent_zshrc b/wincent_zshrc
--- a/wincent_zshrc
+++ b/wincent_zshrc
@@ -4,11 +4,58 @@
 
 # Create a hash table for globally stashing variables without polluting main
 # scope with a bunch of identifiers.
-typeset -A __MORGOTH
+typeset -A __WINCENT
 
-__MORGOTH[ITALIC_ON]=$'\e[3m'
-__MORGOTH[ITALIC_OFF]=$'\e[23m'
+__WINCENT[ITALIC_ON]=$'\e[3m'
+__WINCENT[ITALIC_OFF]=$'\e[23m'
 
+#
+# Teh H4xx
+#
+
+if [ "$(uname)" = "Darwin" ]; then
+  # Suppress unwanted Homebrew-installed stuff.
+  if [ -e /usr/local/share/zsh/site-functions/_git ]; then
+    mv -f /usr/local/share/zsh/site-functions/{,disabled.}_git
+  fi
+
+  # Set 60 fps key repeat rate
+  #
+  # Equivalent to the fatest rate acheivable with:
+  #
+  #     defaults write NSGlobalDomain KeyRepeat -int 1
+  #
+  # But doesn't require a logout and will get restored every time we open a
+  # shell (for example, if somebody manipulates the slider in the UI).
+  #
+  # Fastest rate available from UI corresponds to:
+  #
+  #     defaults write NSGlobalDomain KeyRepeat -int 2
+  #
+  # Slowest rate available from UI corresponds to:
+  #
+  #     defaults write NSGlobalDomain KeyRepeat -int 120
+  #
+  # Values at each slider position in UI, from slowest to fastest:
+  #
+  # - 120 -> 2 seconds (ie. .5 fps)
+  # - 90 -> 1.5 seconds (ie .6666 fps)
+  # - 60 -> 1 second (ie 1 fps)
+  # - 30 -> 0.5 seconds (ie. 2 fps)
+  # - 12 -> 0.2 seconds (ie. 5 fps)
+  # - 6 -> 0.1 seconds (ie. 10 fps)
+  # - 2 -> 0.03333 seconds (ie. 30 fps)
+  #
+  # See: https://github.com/mathiasbynens/dotfiles/issues/687
+  #
+  if command -v dry &> /dev/null; then
+    dry 0.0166666666667 > /dev/null
+  fi
+fi
+
+#
+# Completion
+#
 
 fpath=($HOME/.zsh/completions $fpath)
 
@@ -35,11 +82,24 @@ zstyle ':completion:*:complete:(cd|pushd):*' tag-order 'local-directories named-
 
 # Categorize completion suggestions with headings:
 zstyle ':completion:*' group-name ''
-zstyle ':completion:*:descriptions' format %F{default}%B%{$__MORGOTH[ITALIC_ON]%}--- %d ---%{$__MORGOTH[ITALIC_OFF]%}%b%f
+zstyle ':completion:*:descriptions' format %F{default}%B%{$__WINCENT[ITALIC_ON]%}--- %d ---%{$__WINCENT[ITALIC_OFF]%}%b%f
 
 # Enable keyboard navigation of completions in menu
 # (not just tab/shift-tab but cursor keys as well):
 zstyle ':completion:*' menu select
+
+#
+# Correction
+#
+
+# exceptions to auto-correction
+alias bundle='nocorrect bundle'
+alias cabal='nocorrect cabal'
+alias man='nocorrect man'
+alias mkdir='nocorrect mkdir'
+alias mv='nocorrect mv'
+alias stack='nocorrect stack'
+alias sudo='nocorrect sudo'
 
 #
 # Prompt
@@ -130,7 +190,7 @@ export SPROMPT="zsh: correct %F{red}'%R'%f to %F{red}'%r'%f [%B%Uy%u%bes, %B%Un%
 #
 
 export HISTSIZE=100000
-export HISTFILE="$HOME/.cache/zsh/histfile"
+export HISTFILE="$HOME/.history"
 export SAVEHIST=$HISTSIZE
 
 #
@@ -142,8 +202,8 @@ setopt AUTO_PARAM_SLASH        # tab completing directory appends a slash
 setopt AUTO_PUSHD              # [default] cd automatically pushes old dir onto dir stack
 setopt AUTO_RESUME             # allow simple commands to resume backgrounded jobs
 setopt CLOBBER                 # allow clobbering with >, no need to use >!
-#setopt CORRECT                 # [default] command auto-correction
-#setopt CORRECT_ALL             # [default] argument auto-correction
+setopt CORRECT                 # [default] command auto-correction
+setopt CORRECT_ALL             # [default] argument auto-correction
 setopt NO_FLOW_CONTROL         # disable start (C-s) and stop (C-q) characters
 setopt NO_HIST_IGNORE_ALL_DUPS # don't filter non-contiguous duplicates from history
 setopt HIST_FIND_NO_DUPS       # don't show dupes when searching
@@ -155,7 +215,7 @@ setopt INTERACTIVE_COMMENTS    # [default] allow comments, even in interactive s
 setopt LIST_PACKED             # make completion lists more densely packed
 setopt MENU_COMPLETE           # auto-insert first possible ambiguous completion
 setopt NO_NOMATCH              # [default] unmatched patterns are left unchanged
-#setopt PRINT_EXIT_VALUE        # [default] for non-zero exit status
+setopt PRINT_EXIT_VALUE        # [default] for non-zero exit status
 setopt PUSHD_IGNORE_DUPS       # don't push multiple copies of same dir onto stack
 setopt PUSHD_SILENT            # [default] don't print dir stack after pushing/popping
 setopt SHARE_HISTORY           # share history across shells
@@ -168,12 +228,11 @@ setopt SHARE_HISTORY           # share history across shells
 autoload -U select-word-style
 select-word-style bash # only alphanumeric chars are considered WORDCHARS
 
-#source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
-#ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=59'
+source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
+ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=59'
 
 # NOTE: must come after select-word-style.
-source $ZDOTDIR/plugins/zsh-history-substring-search/zsh-history-substring-search.plugin.zsh
-
+source /usr/local/share/zsh-history-substring-search/zsh-history-substring-search.zsh
 
 # Note that this will only ensure unique history if we supply a prefix
 # before hitting "up" (ie. we perform a "search"). HIST_FIND_NO_DUPS
@@ -233,16 +292,14 @@ bindkey '^Z' fg-bg
 # Other
 #
 
-source $HOME/.config/zsh/aliases.zsh
-source $HOME/.config/zsh/exports.zsh
-source $HOME/.config/zsh/functions.zsh
-#source $HOME/.zsh/common
-#source $HOME/.config/zsh/colors.zsh
-#source $HOME/.zsh/exports
-#source $HOME/.zsh/functions
-#source $HOME/.zsh/hash
-#source $HOME/.zsh/path
-#source $HOME/.zsh/vars
+source $HOME/.zsh/aliases
+source $HOME/.zsh/common
+source $HOME/.zsh/colors
+source $HOME/.zsh/exports
+source $HOME/.zsh/functions
+source $HOME/.zsh/hash
+source $HOME/.zsh/path
+source $HOME/.zsh/vars
 
 #
 # Third-party
@@ -340,7 +397,7 @@ function -report-start-time() {
       SECS="$((~~$SECS))s"
     fi
     ELAPSED="${ELAPSED}${SECS}"
-    export RPROMPT="%F{cyan}%{$__MORGOTH[ITALIC_ON]%}${ELAPSED}%{$__MORGOTH[ITALIC_OFF]%}%f $RPROMPT_BASE"
+    export RPROMPT="%F{cyan}%{$__WINCENT[ITALIC_ON]%}${ELAPSED}%{$__WINCENT[ITALIC_OFF]%}%f $RPROMPT_BASE"
     unset ZSH_START_TIME
   else
     export RPROMPT="$RPROMPT_BASE"
@@ -348,7 +405,7 @@ function -report-start-time() {
 }
 add-zsh-hook precmd -report-start-time
 
-#add-zsh-hook precmd bounce
+add-zsh-hook precmd bounce
 
 function -auto-ls-after-cd() {
   emulate -L zsh
@@ -362,17 +419,17 @@ add-zsh-hook chpwd -auto-ls-after-cd
 
 # Remember each command we run.
 function -record-command() {
-  __MORGOTH[LAST_COMMAND]="$2"
+  __WINCENT[LAST_COMMAND]="$2"
 }
 add-zsh-hook preexec -record-command
 
 # Update vcs_info (slow) after any command that probably changed it.
 function -maybe-show-vcs-info() {
-  local LAST="$__MORGOTH[LAST_COMMAND]"
+  local LAST="$__WINCENT[LAST_COMMAND]"
 
   # In case user just hit enter, overwrite LAST_COMMAND, because preexec
   # won't run and it will otherwise linger.
-  __MORGOTH[LAST_COMMAND]="<unset>"
+  __WINCENT[LAST_COMMAND]="<unset>"
 
   # Check first word; via:
   # http://tim.vanwerkhoven.org/post/2012/10/28/ZSH/Bash-string-manipulation
@@ -395,3 +452,22 @@ zstyle ':completion:*:*:cdr:*:*' menu selection
 
 # fall through to cd if cdr is passed a non-recent dir as an argument
 zstyle ':chpwd:*' recent-dirs-default true
+
+# Local and host-specific overrides.
+
+LOCAL_RC=$HOME/.zshrc.local
+test -f $LOCAL_RC && source $LOCAL_RC
+
+HOST_RC=$HOME/.zsh/host/$(hostname -s | tr '[:upper:]' '[:lower:]')
+test -f $HOST_RC && source $HOST_RC
+
+#
+# /etc/motd
+#
+
+if [ -e /etc/motd ]; then
+  if ! cmp -s $HOME/.hushlogin /etc/motd; then
+    tee $HOME/.hushlogin < /etc/motd
+  fi
+fi
+t
